import { Link, Route, Routes } from "react-router-dom";
import { AppShell } from "./components/AppShell";
import { EmptyState } from "./components/EmptyState";

function HomePage() {
  return (
    <section className="hero-panel">
      <p className="eyebrow">Generated by Jostavan</p>
      <h1>Ready for your product logic.</h1>
      <p>
        This deterministic shell is replaced and extended by the sandbox agent
        with app-specific pages, data flows, and backend functions.
      </p>
      <div className="actions">
        <Link to="/dashboard">Open dashboard</Link>
      </div>
    </section>
  );
}

function DashboardPage() {
  return (
    <EmptyState
      title="Dashboard foundation"
      text="The build agent should replace this page with the app-specific workspace."
    />
  );
}

export function App() {
  return (
    <AppShell>
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/dashboard" element={<DashboardPage />} />
      </Routes>
    </AppShell>
  );
}
